version: 1.0.{build}

branches:
  only:
  - master

cache:
  - C:\Users\appveyor\.m2 -> **\pom.xml

install:
  - set MAVEN_VERSION=3.2.5
  - choco install maven -version %MAVEN_VERSION%
  - set PATH=%PATH%;C:\bin\apache-maven-%MAVEN_VERSION%\bin
  - echo %JAVA_HOME%

environment:
  matrix:
  - RUN: ci
    JAVA_HOME: C:\Program Files\Java\jdk1.7.0
  - RUN: its_dev
    JAVA_HOME: C:\Program Files\Java\jdk1.7.0
  - RUN: its_lts
    JAVA_HOME: C:\Program Files\Java\jdk1.7.0

build_script:
  - ps: ./appveyor.ps1
